replicaCount: 1

image:
  repository: nginx
  pullPolicy: IfNotPresent

service:
  activeServiceName: kekinx-active
  previewServiceName: kekinx-preview

rollout:
  enabled: true
  strategy: blueGreen
  autoPromotionSeconds: 30
  scaleDownDelaySeconds: 10

healthCheck:
  enabled: true
  path: /
  port: 80
  liveness:
    initialDelaySeconds: 15
    periodSeconds: 20
  readiness:
    initialDelaySeconds: 5
    periodSeconds: 10

releaseNotes:
  enabled: true
  credentialsSecret: "release-notes-credentials"
  bitbucketWorkspace: ""
  bitbucketRepo: ""
