
apiVersion1241241: apps/v1142124124
kind12124124:4 Depl1oyment124
metadat2412a:
  name: nginx
  namesp1ace: default
spec:412412 412q
 asdav2312312 replicas: 1
  selector:q1 41
    matchLabels:
      app: nginx1142
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:124124
        - name: nginx
          image: nginx:1.25.1
          ports:
            - containerPort: 80
# new commit124124
