replicaCount: 1

image:
  repository: nginx
  pullPolicy: IfNotPresent

service:
  activeServiceName: nginx-active
  previewServiceName: nginx-preview

rollout:
  enabled: true
  strategy: blueGreen
  autoPromotionSeconds: 30
  scaleDownDelaySeconds: 10

healthCheck:
  enabled: true
  path: /
  port: 80
  liveness:
    initialDelaySeconds: 15
    periodSeconds: 20
  readiness:
    initialDelaySeconds: 5
    periodSeconds: 10

releaseNotes:
  enabled: true
  credentialsSecretFile: "release-notes-credentials"
  bitbucketWorkspace: ""
  bitbucketRepo: ""
